### DISCUSSION TITLE
Changing Octomap resolution in humble

### DISCUSSION THREAD

**Discussion by agraussgrimbergen** [moveit/moveit2#3071] [Q&A] [answered]
For ROS1 there was a param that could be set to change the resolution of the octomap voxels. Is there a similar configuration to set for ROS2? I am currently using humble specifically. I have only seen padding settings in the sensors.yaml file.

Any help would be greatly appreciated!

**Comment by Danilrivero** [comment, marked as answer]
You can change it by setting up another field like this:

```yaml
sensors:
  - default_sensor
default_sensor:
  filtered_cloud_topic: filtered_cloud
  max_range: 3.0
  max_update_rate: 1.0
  padding_offset: 0.01
  padding_scale: 0.01
  point_cloud_topic: /camera/depth/color/points
  point_subsample: 1
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
octomap_resolution: 0.02
```

Alternatively, you can setup your values like this in your launch file:

```yaml
octomap_updater = { 'octomap_resolution': 0.02 }
```

And add it as a **parameter** to your _move_group_ node.
