### ISSUE TITLE
Simplify KDL joint weights parameters

### ISSUE THREAD

**Issue by sea-bass** [moveit/moveit2#2756]
In https://github.com/ros-planning/moveit2/pull/2750 we introduced a stop-gap for fixing the KDL IK plugin parameters so that CI passes due to some breaking changes in `generate_parameter_library`.

Ideally, we should change `generate_parameter_library` to support a simpler way of expressing these weights, for example:

```yaml
  weights:
    joint1: 2.0
    joint5: 1.5
```
