### ISSUE TITLE
Add missing ParallelGripperCommand controller type

### ISSUE THREAD

**Issue by mrjogo** [moveit/moveit2#3017]
### Description

At some point, ros2_controllers deprecated `position_controllers/GripperActionController` (and its associated action `control_msgs/GripperCommand`), and using it now gives this message:

```
[Deprecated]: the `position_controllers/GripperActionController` and `effort_controllers::GripperActionController` controllers are replaced by 'parallel_gripper_controllers/GripperActionController' controller
```

However, `parallel_gripper_controllers/GripperActionController` uses the action `control_msgs/ParallelGripperCommand`, which has not yet been added to `MoveItSimpleControllerManager`, so trying to use it gives an error.

### ROS Distro

Jazzy

### OS and version

Ubuntu 24.04

### Source or binary build?

Binary

### If binary, which release version?

2.10.0

### Which RMW are you using?

FastRTPS

### Steps to Reproduce

Create a `moveit_controllers.yaml` with `type: ParallelGripperCommand`:

```yaml
/**:
  ros__parameters:
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
    moveit_simple_controller_manager:
      controller_names:
        - some_controller

      some_controller:
        action_ns: gripper_cmd
        type: ParallelGripperCommand
        default: true
        max_effort: 1000.0
        joints:
          - some_joint
```

### Expected behavior

MoveIt comes up and can command the gripper.

### Actual behavior

MoveIt throws an error and none of the `MoveItSimpleControllerManager` controllers come up.

### Backtrace or Console output

```
[move_group-7] [ERROR] [1727825074.412220666] [move_group.moveit.moveit.plugins.simple_controller_manager]: Unknown controller type: ParallelGripperCommand
```
