### ISSUE TITLE
can not controller the manipulator over Rviz2 when in namespace

### ISSUE THREAD

**Issue by adamanov** [moveit/moveit2#3170]
### Description

Hello,

In my current application I am trying to combine clearpath jackal with open manipulator pro arm and control the arm firstly over rviz2 and after over my application package. 

Sofar I could succesefully load all controllers in namespace i.e. mobile base,  manipulator and gripper, and also could start the moveit2 inside the namespace

Humble, Ubuntu 22, from source

### Expected behavior

Rviz2 action clients being also inside the namespace 

### Actual behavior

Currently I can see the arm inside the rviz

the MotionPlanning section does not work at all, because as i see output from `ros2 topic list` and `ros action list`  
even though the rviz2 node is inside the namespace `/j100_0000/rviz2`  the actions and topics are not inside the namespace. Therefore it is not working. 
How could I fix it and bring the rviz2 action clients inside the namespace?

Thanks in advnace 

![Image](https://github.com/user-attachments/assets/092e2ab5-16cf-4a97-9e7d-b526d9fc9913)

```
robolab@robolab-jackal:~/robolab_ws$ ros2 action list
/execute_trajectory
/j100_0000/arm_controller/follow_joint_trajectory
/j100_0000/execute_trajectory
/j100_0000/gripper_controller/gripper_cmd
/j100_0000/move_action
/j100_0000/sequence_move_group
/move_action
robolab@robolab-jackal:~/robolab_ws$ ros2 action info /move_action
Action: /move_action
Action clients: 2
    //j/1/0/0/_/0/0/0/0rviz2
    //j/1/0/0/_/0/0/0/0rviz2
Action servers: 0
robolab@robolab-jackal:~/r
```

### Backtrace or Console output

```
[ros2_control_node-2] [INFO] [1734425826.817234523] [j100_0000.controller_manager]: Spawning controller_manager RT thread with scheduler priority: 50
[ros2_control_node-2] [WARN] [1734425826.819896643] [j100_0000.controller_manager]: No real-time kernel detected on this system. See [https://control.ros.org/master/doc/ros2_control/controller_manager/doc/userdoc.html] for details on how to enable realtime scheduling.
[ros2_control_node-2] [INFO] [1734425826.857707908] [j100_0000.controller_manager]: Received robot description file.
[ros2_control_node-2] [INFO] [1734425826.858006232] [resource_manager]: Loading hardware 'j100_hardware' 
[ros2_control_node-2] [INFO] [1734425826.858837817] [resource_manager]: Initialize hardware 'j100_hardware' 
[ros2_control_node-2] [INFO] [1734425826.858851375] [j100_hardware]: Name: j100_hardware
[ros2_control_node-2] [INFO] [1734425826.858854249] [j100_hardware]: Number of Joints 4
[ros2_control_node-2] [INFO] [1734425826.860846523] [resource_manager]: Successful initialization of hardware 'j100_hardware'
[ros2_control_node-2] [INFO] [1734425826.860866826] [resource_manager]: Loading hardware 'open_manipulator_p_with_gripper_ros2_control' 
[ros2_control_node-2] [INFO] [1734425826.861600021] [resource_manager]: Initialize hardware 'open_manipulator_p_with_gripper_ros2_control' 
[ros2_control_node-2] [INFO] [1734425826.861773976] [DynamixelHardware]: joint_id 0: 1
[ros2_control_node-2] [INFO] [1734425826.861778666] [DynamixelHardware]: joint_id 1: 2
[ros2_control_node-2] [INFO] [1734425826.861781366] [DynamixelHardware]: joint_id 2: 3
[ros2_control_node-2] [INFO] [1734425826.861783442] [DynamixelHardware]: joint_id 3: 4
[ros2_control_node-2] [INFO] [1734425826.861785284] [DynamixelHardware]: joint_id 4: 5
[ros2_control_node-2] [INFO] [1734425826.861787133] [DynamixelHardware]: joint_id 5: 6
[ros2_control_node-2] [INFO] [1734425826.861788958] [DynamixelHardware]: joint_id 6: 7
[ros2_control_node-2] [INFO] [1734425826.861793588] [DynamixelHardware]: usb_port: /dev/ttyManipulator
[ros2_control_node-2] [INFO] [1734425826.861795647] [DynamixelHardware]: baud_rate: 1000000
[spawner-5] [INFO] [1734425827.210552668] [j100_0000.spawner_arm_controller]: waiting for service /j100_0000/controller_manager/list_controllers to become available...
[spawner-3] [INFO] [1734425827.232843306] [j100_0000.spawner_joint_state_broadcaster]: waiting for service /j100_0000/controller_manager/list_controllers to become available...
[spawner-6] [INFO] [1734425827.235337364] [j100_0000.spawner_gripper_controller]: waiting for service /j100_0000/controller_manager/list_controllers to become available...
[spawner-4] [INFO] [1734425827.245171701] [j100_0000.spawner_platform_velocity_controller]: waiting for service /j100_0000/controller_manager/list_controllers to become available...
[ros2_control_node-2] [FATAL] [1734425827.262223452] [DynamixelHardware]: [DynamixelWorkbench] Failed to set Position Control Mode!
[ros2_control_node-2] [INFO] [1734425827.374218007] [DynamixelHardware]: Torque enabled
[ros2_control_node-2] [INFO] [1734425827.374350506] [resource_manager]: Successful initialization of hardware 'open_manipulator_p_with_gripper_ros2_control'
[ros2_control_node-2] [INFO] [1734425827.374591073] [resource_manager]: 'configure' hardware 'open_manipulator_p_with_gripper_ros2_control' 
[ros2_control_node-2] [INFO] [1734425827.374600723] [resource_manager]: Successful 'configure' of hardware 'open_manipulator_p_with_gripper_ros2_control'
[ros2_control_node-2] [INFO] [1734425827.374610442] [resource_manager]: 'activate' hardware 'open_manipulator_p_with_gripper_ros2_control' 
[ros2_control_node-2] [INFO] [1734425827.390381397] [resource_manager]: Successful 'activate' of hardware 'open_manipulator_p_with_gripper_ros2_control'
[ros2_control_node-2] [INFO] [1734425827.390393897] [resource_manager]: 'configure' hardware 'j100_hardware' 
[ros2_control_node-2] [INFO] [1734425827.390400008] [resource_manager]: Successful 'configure' of hardware 'j100_hardware'
[ros2_control_node-2] [INFO] [1734425827.390405659] [resource_manager]: 'activate' hardware 'j100_hardware' 
[ros2_control_node-2] [INFO] [1734425827.390410131] [j100_hardware]: Starting ...please wait...
[ros2_control_node-2] [INFO] [1734425827.390414270] [j100_hardware]: System Successfully started!
[ros2_control_node-2] [INFO] [1734425827.390418254] [resource_manager]: Successful 'activate' of hardware 'j100_hardware'
[ros2_control_node-2] [INFO] [1734425827.464280780] [j100_0000.controller_manager]: Loading controller 'arm_controller'
[ros2_control_node-2] [WARN] [1734425827.481614637] [j100_0000.arm_controller]: [Deprecated]: "allow_nonzero_velocity_at_trajectory_end" is set to true. The default behavior will change to false.
[spawner-5] [INFO] [1734425827.487669403] [j100_0000.spawner_arm_controller]: Loaded arm_controller
[ros2_control_node-2] [INFO] [1734425827.488467559] [j100_0000.controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-2] [INFO] [1734425827.502656928] [j100_0000.controller_manager]: Loading controller 'gripper_controller'
[spawner-3] [INFO] [1734425827.503039956] [j100_0000.spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-2] [INFO] [1734425827.534628087] [j100_0000.controller_manager]: Loading controller 'platform_velocity_controller'
[spawner-6] [INFO] [1734425827.536138869] [j100_0000.spawner_gripper_controller]: Loaded gripper_controller
[ros2_control_node-2] [INFO] [1734425827.550624893] [j100_0000.controller_manager]: Configuring controller 'arm_controller'
[ros2_control_node-2] [INFO] [1734425827.551067886] [j100_0000.arm_controller]: No specific joint names are used for command interfaces. Using 'joints' parameter.
[ros2_control_node-2] [INFO] [1734425827.551166169] [j100_0000.arm_controller]: Command interfaces are [position] and state interfaces are [position].
[ros2_control_node-2] [INFO] [1734425827.551215938] [j100_0000.arm_controller]: Using 'splines' interpolation method.
[spawner-4] [INFO] [1734425827.551613421] [j100_0000.spawner_platform_velocity_controller]: Loaded platform_velocity_controller
[ros2_control_node-2] [INFO] [1734425827.553948783] [j100_0000.arm_controller]: Controller state will be published at 50.00 Hz.
[ros2_control_node-2] [INFO] [1734425827.564543687] [j100_0000.arm_controller]: Action status changes will be monitored at 20.00 Hz.
[ros2_control_node-2] [INFO] [1734425827.582667766] [j100_0000.controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-2] [INFO] [1734425827.582790368] [j100_0000.joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[ros2_control_node-2] [INFO] [1734425827.614679480] [j100_0000.controller_manager]: Configuring controller 'gripper_controller'
[ros2_control_node-2] [INFO] [1734425827.614819749] [j100_0000.gripper_controller]: Action status changes will be monitored at 20Hz.
[ros2_control_node-2] [INFO] [1734425827.630659724] [j100_0000.controller_manager]: Configuring controller 'platform_velocity_controller'
[spawner-5] [INFO] [1734425827.695830525] [j100_0000.spawner_arm_controller]: Configured and activated arm_controller
[spawner-3] [INFO] [1734425827.727144074] [j100_0000.spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[spawner-6] [INFO] [1734425827.775982266] [j100_0000.spawner_gripper_controller]: Configured and activated gripper_controller
[spawner-4] [INFO] [1734425827.807102843] [j100_0000.spawner_platform_velocity_controller]: Configured and activated platform_velocity_controller
[INFO] [spawner-5]: process has finished cleanly [pid 8307]
[INFO] [spawner-3]: process has finished cleanly [pid 8303]
[INFO] [spawner-6]: process has finished cleanly [pid 8309]
[INFO] [spawner-4]: process has finished cleanly [pid 8305]
[imu_filter_madgwick_node-9] [WARN] [1734425836.792640899] [j100_0000.imu_filter_node]: Still waiting for data on topic imu/data_raw...

```

and here is my controller.yaml file

```
# ! Unfortuntelly moveit is not able to find out the correct controller configuration
# therefore is not starting correctly. The solution is to load jackal and arm controller seperately 
j100_0000:
  controller_manager:
    ros__parameters:
      update_rate: 50  # Hz
      use_sim_time: False

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      platform_velocity_controller:
        type: diff_drive_controller/DiffDriveController

      arm_controller:
        type: joint_trajectory_controller/JointTrajectoryController
        
      gripper_controller:
        type: position_controllers/GripperActionController

  joint_state_broadcaster:
    ros__parameters:
      type: joint_state_broadcaster/JointStateBroadcaster

  platform_velocity_controller:
    ros__parameters:
      type: diff_drive_controller/DiffDriveController

      use_sim_time: False
      left_wheel_names: [ "front_left_wheel_joint", "rear_left_wheel_joint" ]
      right_wheel_names: [ "front_right_wheel_joint", "rear_right_wheel_joint" ]

      # Wheel measurements (when set here, the values in the jackal.urdf are ignored)
      wheel_separation: 0.375
      wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
      wheel_radius: 0.095

      # Wheel separation and radius multipliers (calibrated with 1 bar wheel pressure)
      wheel_separation_multiplier: 1.483 # default: 1.0; 1.5 for clearpath jackal
      left_wheel_radius_multiplier: 0.9534 # default: 1.0
      right_wheel_radius_multiplier: 0.9534 # default: 1.0

      publish_rate: 50.0
      odom_frame_id: odom
      base_frame_id: base_link
      pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
      twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

      open_loop: false
      enable_odom_tf: false # set true for odometry calibration (remember to set publish_tf to false in localization.yaml)
      tf_frame_prefix_enable: false

      cmd_vel_timeout: 0.5
      #publish_limited_velocity: true
      use_stamped_vel: false
      #velocity_rolling_window_size: 10

      # Preserve turning radius when limiting speed/acceleration/jerk
      preserve_turning_radius: true

      # Publish limited velocity
      publish_cmd: true

      # Publish wheel data
      publish_wheel_data: true

      # Velocity and acceleration limits
      # Whenever a min_* is unspecified, default to -max_*
      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.has_jerk_limits: false
      linear.x.max_velocity: 2.0
      linear.x.min_velocity: -2.0
      linear.x.max_acceleration: 20.0
      linear.x.min_acceleration: -20.0
      linear.x.max_jerk: 0.0
      linear.x.min_jerk: 0.0

      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: true
      angular.z.has_jerk_limits: false
      angular.z.max_velocity: 4.0
      angular.z.min_velocity: -4.0
      angular.z.max_acceleration: 25.0
      angular.z.min_acceleration: -25.0
      angular.z.max_jerk: 0.0
      angular.z.min_jerk: 0.0

  arm_controller:
    ros__parameters:
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
      command_interfaces:
        - position
      state_interfaces:
        - position
      # allow_nonzero_velocity_at_trajectory_end: true

  gripper_controller:
    ros__parameters:
      action_monitor_rate: 20.0
      allow_stalling: false
      goal_tolerance: 0.01
      joint: 'gripper'
      max_effort: 0.0
      stall_timeout: 1.0
      stall_velocity_threshold: 0.001
```

and `move_group` node is started correctly

```
move_group-1] [INFO] [1734428365.117730830] [j100_0000.moveit.moveit.core.robot_model]: Loading robot model 'jackal_omp'...
[move_group-1] [WARN] [1734428365.157552725] [j100_0000.moveit.moveit.core.robot_model]: Link imu_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[move_group-1] [WARN] [1734428365.157588321] [j100_0000.moveit.moveit.core.robot_model]: Link gps_0_link has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.
[move_group-1] [INFO] [1734428365.165846820] [j100_0000.moveit.moveit.kinematics.kdl_kinematics_plugin]: Joint weights for group 'arm': 1 1 1 1 1 1
[move_group-1] [INFO] [1734428365.284633803] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1734428365.284744585] [j100_0000.moveit.moveit.ros.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-1] [INFO] [1734428365.285145460] [j100_0000.moveit.moveit.ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-1] [INFO] [1734428365.285341290] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Listening to '/j100_0000/attached_collision_object' for attached collision objects
[move_group-1] [INFO] [1734428365.285346934] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Stopping existing planning scene publisher.
[move_group-1] [INFO] [1734428365.285451867] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Stopped publishing maintained planning scene.
[move_group-1] [INFO] [1734428365.285622683] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-1] [INFO] [1734428365.285669195] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Starting planning scene monitor
[move_group-1] [INFO] [1734428365.285834417] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Listening to '/j100_0000/planning_scene'
[move_group-1] [INFO] [1734428365.285838905] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-1] [INFO] [1734428365.286411470] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Listening to 'collision_object'
[move_group-1] [INFO] [1734428365.286538708] [j100_0000.moveit.moveit.ros.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[rviz2-2] [INFO] [1734428365.286949173] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-2] [INFO] [1734428365.286999069] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[move_group-1] [WARN] [1734428365.287215021] [j100_0000.moveit.moveit.ros.occupancy_map_monitor]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-1] [ERROR] [1734428365.287223831] [j100_0000.moveit.moveit.ros.occupancy_map_monitor]: No 3D sensor plugin(s) defined for octomap updates
[rviz2-2] [INFO] [1734428365.299148638] [rviz2]: Stereo is NOT SUPPORTED
[move_group-1] [INFO] [1734428365.345466232] [j100_0000.moveit.moveit.ros.planning_pipeline]: Successfully loaded planner 'OMPL'
[move_group-1] [INFO] [1734428365.347344917] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.347991798] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.348000750] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.348130125] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.348134469] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.348152717] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.348155995] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.348162575] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.349952168] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.351208442] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.351220557] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.352222962] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.352235696] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.352490972] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.355208998] [j100_0000.moveit.moveit.planners.pilz.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
[move_group-1] [INFO] [1734428365.359237236] [j100_0000.moveit.moveit.planners.pilz.command_planner]: Available plugins: pilz_industrial_motion_planner/PlanningContextLoaderCIRC pilz_industrial_motion_planner/PlanningContextLoaderLIN pilz_industrial_motion_planner/PlanningContextLoaderPTP 
[move_group-1] [INFO] [1734428365.359248136] [j100_0000.moveit.moveit.planners.pilz.command_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderCIRC
[move_group-1] [INFO] [1734428365.360196867] [j100_0000.moveit.moveit.planners.pilz.command_planner]: Registered Algorithm [CIRC]
[move_group-1] [INFO] [1734428365.360204466] [j100_0000.moveit.moveit.planners.pilz.command_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderLIN
[move_group-1] [INFO] [1734428365.360789646] [j100_0000.moveit.moveit.planners.pilz.command_planner]: Registered Algorithm [LIN]
[move_group-1] [INFO] [1734428365.360795617] [j100_0000.moveit.moveit.planners.pilz.command_planner]: About to load: pilz_industrial_motion_planner/PlanningContextLoaderPTP
[move_group-1] [INFO] [1734428365.361344056] [j100_0000.moveit.moveit.planners.pilz.command_planner]: Registered Algorithm [PTP]
[move_group-1] [INFO] [1734428365.361349436] [j100_0000.moveit.moveit.ros.planning_pipeline]: Successfully loaded planner 'Pilz Industrial Motion Planner'
[move_group-1] [INFO] [1734428365.363167155] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.363320901] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.363325575] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.363477463] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.363482378] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.363493870] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.363500915] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.363507906] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.365259409] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.365857293] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.365867017] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.366018012] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.369895367] [j100_0000.moveit.moveit.ros.planning_pipeline]: Successfully loaded planner 'CHOMP'
[move_group-1] [INFO] [1734428365.371684748] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.371831705] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.371836394] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.371994196] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.372013783] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.372026087] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.372029470] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.372036700] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.373783585] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.374110830] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.374116505] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.374371787] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.374382384] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.374757615] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.378629180] [j100_0000.moveit.moveit.ros.planning_pipeline]: Successfully loaded planner 'STOMP'
[move_group-1] [INFO] [1734428365.380530827] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.380769010] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ResolveConstraintFrames'
[move_group-1] [INFO] [1734428365.380780377] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.380958927] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/ValidateWorkspaceBounds'
[move_group-1] [INFO] [1734428365.380969399] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.380991174] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateBounds'
[move_group-1] [INFO] [1734428365.380996361] [j100_0000.move_group]: Try loading adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.381008302] [j100_0000.move_group]: Loaded adapter 'default_planning_request_adapters/CheckStartStateCollision'
[move_group-1] [INFO] [1734428365.382817872] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.383185886] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/AddTimeOptimalParameterization'
[move_group-1] [INFO] [1734428365.383192681] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.383458311] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/ValidateSolution'
[move_group-1] [INFO] [1734428365.383494819] [j100_0000.move_group]: Try loading adapter 'default_planning_response_adapters/DisplayMotionPath'
[move_group-1] [INFO] [1734428365.383853268] [j100_0000.move_group]: Loaded adapter 'default_planning_response_adapters/DisplayMotionPath'
[rviz2-2] [WARN] [1734428365.399405367] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[move_group-1] [INFO] [1734428365.411223222] [j100_0000.moveit.moveit.plugins.simple_controller_manager]: Added FollowJointTrajectory controller for arm_controller
[move_group-1] [INFO] [1734428365.411266602] [j100_0000.moveit.moveit.plugins.simple_controller_manager]: Max effort set to 0.0
[move_group-1] [INFO] [1734428365.412333131] [j100_0000.moveit.moveit.plugins.simple_controller_manager]: Added GripperCommand controller for gripper_controller
[move_group-1] [INFO] [1734428365.412428017] [j100_0000.moveit.moveit.plugins.simple_controller_manager]: Returned 2 controllers in list
[move_group-1] [INFO] [1734428365.412447052] [j100_0000.moveit.moveit.plugins.simple_controller_manager]: Returned 2 controllers in list
[move_group-1] [INFO] [1734428365.412627104] [j100_0000.moveit.moveit.ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-1] [INFO] [1734428365.412648678] [j100_0000.move_group]: MoveGroup debug mode is ON
[rviz2-2] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-2]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[move_group-1] [INFO] [1734428365.421749832] [j100_0000.moveit.moveit.planners.pilz.move_group_sequence_action]: initialize move group sequence action
[move_group-1] [INFO] [1734428365.422769844] [j100_0000.moveit.moveit.planners.pilz.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
[move_group-1] [INFO] [1734428365.422938476] [j100_0000.moveit.moveit.planners.pilz.joint_limits_aggregator]: Reading limits from namespace robot_description_planning
[move_group-1] [INFO] [1734428365.423258354] [j100_0000.moveit.moveit.ros.move_group.executable]: 
[move_group-1] 
[move_group-1] ********************************************************
[move_group-1] * MoveGroup using: 
[move_group-1] *     - apply_planning_scene_service
[move_group-1] *     - clear_octomap_service
[move_group-1] *     - get_group_urdf
[move_group-1] *     - load_geometry_from_file
[move_group-1] *     - CartesianPathService
[move_group-1] *     - execute_trajectory_action
[move_group-1] *     - get_planning_scene_service
[move_group-1] *     - kinematics_service
[move_group-1] *     - move_action
[move_group-1] *     - motion_plan_service
[move_group-1] *     - query_planners_service
[move_group-1] *     - state_validation_service
[move_group-1] *     - save_geometry_to_file
[move_group-1] *     - SequenceAction
[move_group-1] *     - SequenceService
[move_group-1] ********************************************************
[move_group-1] 
[move_group-1] [INFO] [1734428365.423276947] [j100_0000.moveit.moveit.ros.move_group.context]: MoveGroup context using pipeline ompl
[move_group-1] [INFO] [1734428365.423281626] [j100_0000.moveit.moveit.ros.move_group.context]: MoveGroup context initialization complete
[move_group-1] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-1] Loading 'move_group/ClearOctomapService'...
[move_group-1] Loading 'move_group/GetUrdfService'...
[move_group-1] Loading 'move_group/LoadGeometryFromFileService'...
[move_group-1] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-1] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-1] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-1] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-1] Loading 'move_group/MoveGroupMoveAction'...
[move_group-1] Loading 'move_group/MoveGroupPlanService'...
[move_group-1] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-1] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-1] Loading 'move_group/SaveGeometryToFileService'...
[move_group-1] Loading 'pilz_industrial_motion_planner/MoveGroupSequenceAction'...
[move_group-1] Loading 'pilz_industrial_motion_planner/MoveGroupSequenceService'...
[move_group-1] 
[move_group-1] You can start planning now!
[move_group-1] 
[rviz2-2] [WARN] [1734428365.425869388] [rcl.logging_rosout]: 

```

with following launch file 

```
    moveit_config = get_moveit_config(robot_name="jackal_manipulation", control_type="real")

    if moveit_config is None:
        return LaunchDescription([])
    
    rviz_config = os.path.join(
        get_package_share_directory("omp_moveit_config"),
        "rviz",
        "move_group.rviz")

    group_manipulators_action = GroupAction(
        actions=[
            PushRosNamespace("j100_0000"),
            Node(
                package="moveit_ros_move_group",
                executable="move_group",
                output="screen",
                parameters=[moveit_config.to_dict()],
                arguments=["--ros-args", "--log-level", "info"],
                remappings=[
                    ('joint_states', 'platform/joint_states'),
                    ('/tf', 'tf'),
                    ('/tf_static', 'tf_static'),
                ],
            ),
            Node(
                package="rviz2",
                executable="rviz2",
                name="rviz2",
                output="log",
                arguments=["-d", rviz_config],
                remappings=[
                    ('joint_states', 'platform/joint_states'),
                    ('/tf', 'tf'),
                    ('/tf_static', 'tf_static'),
                ],
            ),
        ]
    )
    ld = LaunchDescription()
    ld.add_action(ros2_control_hardware_type)
    ld.add_action(group_manipulators_action)

```
