### ISSUE TITLE
MoveIt Setup Assistant does not honor `action_ns` or `default` values

### ISSUE THREAD

**Issue by jimmy-mcelwain** [moveit/moveit2#3314]
### Description

When I fill out the MoveIt Controllers section in the MoveIt Setup Assistant with the following configuration 

![MoveIt Controllers Section](https://github.com/user-attachments/assets/09cb8987-5138-4446-ba86-dd6353180c40) 

and then I generate the files, I get the resulting `moveit_controllers.yaml`

```
# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - my_fjt_ctrl

  my_fjt_ctrl:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    action_ns: ""
    default: false
```

Note that `action_ns` and `default` are both defined twice. Seemingly once with the values I put, and once with the default values. This obviously causes problems. 

I've also tried this without changing the `default` from `true`, and the action namespace still gets set to the wrong thing. 

Probably related to https://github.com/moveit/moveit2/issues/1514. Maybe that fix had problems. 

### ROS Distro

Humble

### OS and version

Ubuntu 22.04

### Source or binary build?

Binary

### If binary, which release version?

2.5.7

### Which RMW are you using?

None

### Steps to Reproduce

Go through the MSA and fill out non-default values in the MoveIt Controllers section 

### Expected behavior

`follow_joint_trajectory` should be empty and `default` should be set to `false`.  

### Actual behavior

The `action_ns` is set to both `follow_joint_trajectory` and empty, and `default` is set to both `true` and `false`
