### ISSUE TITLE
joints weights

### ISSUE THREAD

**Issue by fp018** [moveit/moveit2#3354]
### Description

Hi! 

I am trying to set KDL **joint weights** from the configuration file _kinematics.yaml_ as:

```
  joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
  weights:
    joint1: 2.0
    joint2: 1.5
    joint3: 2.0
    joint4: 1.5
    joint5: 2.0
    joint6: 1.5
```

However, when I launch the demo, created with the setup assistant, the default weights are set rather than the one from the config file.
Is it a bug or am I writing it wrongly?

Thanks in advance!

### ROS Distro

Jazzy

### OS and version

Ubuntu 24.0

### Source or binary build?

Source

### Which RMW are you using?

None

### Steps to Reproduce

Create a new robot model with the setup assistant and set 

```
  joints: ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
  weights:
    joint1: 2.0
    joint2: 1.5
    joint3: 2.0
    joint4: 1.5
    joint5: 2.0
    joint6: 1.5
```
in the config file _kinematics.yaml_

### Expected behavior

The joint weights from the config file kinematics.yaml are set when launching the demo. 

### Actual behavior

The default joint weights are set.
