### ISSUE TITLE
occupancy_map_monitor::OccupancyMapUpdater does not exist

### ISSUE THREAD

**Issue by shrutichakraborty** [moveit/moveit2#3452]
### Description

Hi! I am on ubuntu22.04 using ros2 humble. I have a UR10E with a realsense D435i camera, the ros2 drivers for the camera are setup and functional and I wanted to be able to visualise the depth pointcloud  as an octomap to use it for collision avoidance when planning trajectories with moveit.  I followed the moveit2 perception pipeline tutorial https://github.com/RoboticsYY/moveit_tutorials/blob/ros2/doc/perception_pipeline/config/sensors_3d.yaml. 

### ROS Distro

Humble

### OS and version

Ubuntu22.04

### Source or binary build?

Source

### Which RMW are you using?

None

### Steps to Reproduce

-

### Expected behavior

-

### Actual behavior

However, I get the following error: 

```
[move_group-1] [ERROR] [1744898112.368041271] [moveit.ros.occupancy_map_monitor.middleware_handle]: Exception while loading octomap updater 'occupancy_map_monitor/PointCloudOctomapUpdater': According to the loaded plugin descriptions the class occupancy_map_monitor/PointCloudOctomapUpdater with base class type occupancy_map_monitor::OccupancyMapUpdater does not exist. Declared types are 
[move_group-1] 
[move_group-1] [ERROR] [1744898112.368061282] [moveit.ros.occupancy_map_monitor]: Failed to load sensor: `sensor1` of type: `occupancy_map_monitor/PointCloudOctomapUpdater`
[move_group-1] [ERROR] [1744898112.368075222] [moveit.ros.occupancy_map_monitor.middleware_handle]: Exception while loading octomap updater 'occupancy_map_monitor/DepthImageOctomapUpdater': According to the loaded plugin descriptions the class occupancy_map_monitor/DepthImageOctomapUpdater with base class type occupancy_map_monitor::OccupancyMapUpdater does not exist. Declared types are 
[move_group-1] 
[move_group-1] [ERROR] [1744898112.368081582] [moveit.ros.occupancy_map_monitor]: Failed to load sensor: `sensor2` of type: `occupancy_map_monitor/DepthImageOctomapUpdater`

```

### Backtrace or Console output

My sensors_3d.yaml file is :

```
sensors:  ["sensor1", "sensor2"]
sensor1:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/camera/depth/color/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: filtered_cloud
sensor2:
    sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera/camera/aligned_depth_to_color/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 5.0
    shadow_threshold: 0.2
    padding_scale: 4.0
    padding_offset: 0.03
    max_update_rate: 1.0
    skip_vertical_pixels: 4
    skip_horizontal_pixels: 6
    filtered_cloud_topic: filtered_cloud

```

My moveit_config launch file contains: 

```
 moveit_config = (
        MoveItConfigsBuilder("ur", package_name="sri_ur_moveit_config")
        .robot_description(file_path = description_file_path,
                           mappings = xacro_arguments)
        .robot_description_semantic(file_path = moveit_semantics_file_path)
        .robot_description_kinematics(file_path = moveit_kinematics_file_path)
        .planning_pipelines(pipelines=["ompl", "pilz_industrial_motion_planner"])
        .planning_pipelines(default_planning_pipeline="ompl")
        # .planning_adapters(default_planner_request_adapters="AddTimeOptimalParameterization")
        .planning_scene_monitor(
            publish_robot_description=True, publish_robot_description_semantic=True
        )
        .trajectory_execution(file_path = controllers_config_file_path, moveit_manage_controllers = True)
        .joint_limits(file_path = moveit_joint_limits_file_path)
        .pilz_cartesian_limits(file_path = pilz_cartesian_limits_file_path)
        .sensors_3d(file_path= sensors_3d_filepath)

    ).to_moveit_configs()


    # Load  ExecuteTaskSolutionCapability so we can execute found solutions in simulation
    # move_group_capabilities = {"capabilities": "move_group/ExecuteTaskSolutionCapability"}

    # print("MoveIt config dictionary:", moveit_config.to_dict())

    # Start the actual move_group node/action server
    move_group_node = Node(
        package="moveit_ros_move_group",
        executable="move_group",
        output="screen",
        parameters=[
            moveit_config.to_dict(),
            {
            "octomap_plugin_package": "moveit_ros_occupancy_map_monitor",
            "octomap_plugin_xml": "plugin_description.xml"
        }
            # trajectory_execution,
            # {"use_sim_time": use_sim_time},
            # move_group_capabilities,
        ],
        # arguments=['--ros-args', '--log-level', "debug"]
    )


``` 

I checked that I do have `ros-humble-moveit-ros-occupancy-map-monitor` installed. I tried to follow the advice on #2642 and install `ros-humble-moveit-ros-perception` but I get the following error: 

```
The following additional packages will be installed:
  freeglut3 freeglut3-dev
The following NEW packages will be installed:
  freeglut3 freeglut3-dev ros-humble-moveit-ros-perception
0 upgraded, 3 newly installed, 0 to remove and 3 not upgraded.
Need to get 333 kB/533 kB of archives.
After this operation, 2,738 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://packages.ros.org/ros2/ubuntu jammy/main amd64 ros-humble-moveit-ros-perception amd64 2.5.8-1jammy.20250210.225103
  404  Not Found [IP: 64.50.236.52 80]
E: Failed to fetch http://packages.ros.org/ros2/ubuntu/pool/main/r/ros-humble-moveit-ros-perception/ros-humble-moveit-ros-perception_2.5.8-1jammy.20250210.225103_amd64.deb  404  Not Found [IP: 64.50.236.52 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?


```

Any fixes?
